### ISSUE TITLE
Additional Request Headers changed to lower case

### ISSUE THREAD

**Issue by vonboth** [jarrodek/ChromeRestClient#1042]
I'm adding an additional request header: X-CSRF-Token

ARC changes it to "X-Csrf-Token" and is therefor not any longer detected by the PHP framework I use.

ARC should not change the string input for the header name as this might be critical.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
ARC itself doesn't change the headers string you add to the input field.
The transformation is made on the JavaScript Headers object. It is worth to mention that headers (as per http spec) are case insensitive so any software that is counting on case sensitivity of headers field of the HTTP message is wrong by design.
This means that this issue should be reported on your framework's issue tracker.

Closing as WAI
