### ISSUE TITLE
Sending request with XHR enabled is stuck on loading

### ISSUE THREAD

**Issue by blaataap** [jarrodek/ChromeRestClient#1075]
Im doing a simple get request with XHR enabled and the blue loading bar keeps loading but no response is shown. 

## Expected outcome
What should happen?
I expected to have to given response of the server instead of a loading bar

## Actual outcome
What happened?
I just get a loading bar even after having it loading for 5-10 mins nothing happened

## Versions
App: 10.0.3
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. Create a simple get request with XHR enabled
2. Add application/json and in my case asp.net verification token headers
3. Click send

**Comment by jarrodek** [comment]
Hi, Thank you for the issue report.
Today I'll send an update with the fix.

**Comment by psyuhen** [comment]
In the use of ARC,
During program debugging,
1.  send a POST request, ARC normal.
2.  Restart the program application(also debugging).
3. Once again, the same request (step 1) is sent by ARC, and the button is stuck in Abort, and the memory is already exploding
4. The request is not successful, and is stuck is in Abort, cancel it , send again, the problem is not solved.
5. Check out the chrome task manager and find that the memory has been going up.
