### ISSUE TITLE
Saved service end-point names

### ISSUE THREAD

**Issue by bijithbalan** [jarrodek/ChromeRestClient#1084]
The service end-point names under the 'Saved' tab are saved in lower case even when we try to save with upper case words

## Expected outcome
The case of the service end-point names under Saved tab should be unchanged.

## Actual outcome
The case of the saved end-point names under Saved tab are all in lower case.

## Versions
App: 10.0.3
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
The names aren't actually saved lower case. However for read optimization when saved menu component reads list of request from the data store it only reads keys instead of reading entire object. Keys are normalized to lower case.

When you open saved request panel the names are in correct case.

To fix it I would actually need to read each the object from the datastore which costs few processor cycles. But is should be fixed.
