### ISSUE TITLE
Ubuntu 16.04: Application icon is grey, no option to launch, clicking "ARC cookie exchange" leads to chrome store link.

### ISSUE THREAD

**Issue by pattrickrice** [jarrodek/ChromeRestClient#1129]
Title explains it all. Just installed the extension. The only options are 

- "ARC cookie exchange"
- "remove from chrome"
- "hide in Chrome menu"
- and "manage extensions"

None of them open the application which gives the impression the application is somehow disabled or broken.

**Comment by jarrodek** [comment]
The extension is a proxy to synchronize cookies between Chrome application and to make a request via Chrome's XHR instead of application's socket.

Chrome applications are deprecated (all of them, not only ARC). Please, install client from https://install.advancedrestclient.com/#/install
Soon all Chrome applications will be removed from Chrome.
