### ISSUE TITLE
Navigation drawer not opening

### ISSUE THREAD

**Issue by vik17ag** [jarrodek/ChromeRestClient#1133]
Your description here

## Expected outcome
What should happen?
On clicking burger icon, nav drawer to open

## Actual outcome
What happened?
It does not open 

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

## Steps to reproduce
1. click on burger icon menu
2. 
3.

**Comment by jarrodek** [comment]
This is fixed in Desktop application. Please, install new version from https://install.advancedrestclient.com/

Since Chrome apps are scheduled to be removed from Chrome very soon I will not fix this issue. Sorry for that.
Desktop client offers much more new features. I strongly encourage to upgrade the application.
