### ISSUE TITLE
I cannot find option to add certificate

### ISSUE THREAD

**Issue by mdasif114** [jarrodek/ChromeRestClient#1144]
I have referred the video which is published on https://restforchrome.blogspot.com/2016/04/advanced-rest-client.html

But, I could not figure out the security options from the app as it is opened in new window.

## Expected outcome
Response Body

## Actual outcome
Install self signed certificate in Chrome
The app can't work if the self-signed certificate is not installed in Chrome.

net::ERR_CERT_AUTHORITY_INVALID

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36

## Steps to reproduce
1. Opened Advance Rest client app from chrome store
2. When I hit send button I get the above error

**Comment by jarrodek** [comment]
It is very hard to make a workaround for Chrome security options. 
Please refer to the cr-bug (https://bugs.chromium.org/p/chromium/issues/detail?id=603104) for reasons why it is not going to be fixed in the app.
I suggest to install desktop client as it does not have such limitations: https://install.advancedrestclient.com/

**Comment by mdasif114** [comment]
Ok, thanks I got it.

*Best Regards,*


*Mohammed AsifMobile: +91- 9677018189*
