### ISSUE TITLE
Minimize the menu make it unresizeable

### ISSUE THREAD

**Issue by haripet** [jarrodek/ChromeRestClient#1170]
Dear developers,

I tried your software, and resized the menu bar on the left side.  I pulled it maximum to the left side and it is still there, with no option to pull it back.
Restart not help, but at least i found the save options on the far corner, behind the menu bar.
## Expected outcome
Minimum menu bar, with options to change size back to normal.

## Actual outcome
No option to resize after minimized the menu bar.
## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

## Steps to reproduce
1. Grab menu bar resizer line.
2. Pull it to the far left.
3. Release the resizer line.

**Comment by jarrodek** [comment]
Hi,
This is fixed in desktop client. If you can, please, install desktop client from https://install.advancedrestclient.com/install

Note, you will have to move your data from Chrome application to desktop client manually using import/export options in settings.

I can't currently update Chrome application as this will cause all user won't be able to install it on other than Chromebook devices.
