### ISSUE TITLE
Image preview in HTTP Response looks ugly

### ISSUE THREAD

**Issue by mstup** [jarrodek/ChromeRestClient#1171]
HTTP response with content-type of image (png, jpeg, etc.) looks like attempt to show text instead the real image graphics.

## Expected outcome
Show image in user friendly way.

## Actual outcome
Text attempt to show binary data.

## Versions
App: 10.0.12
Platform: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

## Steps to reproduce
1. Request external service that return an image in response.
for example: https://hackernoon.com/hn-images/0*4ty0Adbdg4dsVBo3.png

**Comment by mstup** [comment]
![1171](https://user-images.githubusercontent.com/16793676/64340690-6deea300-cfef-11e9-9141-5ddae509bf50.png)

**Comment by jarrodek** [comment]
Hi,
Sorry for late response. 
The image you posted is from Chrome application. Actively maitained is Desktop client. You can get it from https://install.advancedrestclient.com/install

Version 14 (now in beta) will have dedicated images preview. It also has PDF view to avoid binary data rendering.
I am closing iot as fixed in Ddesktop client.
