### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Surefyre** [jarrodek/ChromeRestClient#1175]
Can we have an 'Ignore SSL cert' option please? So many API test systems have invalid SSL certs.

Equivalent to CURLOPT_SSL_VERIFYHOST / CURLOPT_SSL_VERIFYPEER

Thanks

**Comment by jarrodek** [comment]
Hi,
Chrome apps won't support this option and it is not  up to me. Because of the limitations a new ARC was created (the desktop client). You can download it from: https://install.advancedrestclient.com/install

You may need to transfer your data from one app to another. Follow these instructions for that: https://docs.advancedrestclient.com/moving-from-chrome-application-to-desktop-client
