### ISSUE TITLE
Not able to select content-type, its missing

### ISSUE THREAD

**Issue by JoelChak** [jarrodek/ChromeRestClient#341]

**Comment by jarrodek** [comment]
It has been removed due to many requests from the community. It caused more confusion than helped.
It's basically the content type header. Nothing more. When you switch method to the one containing entity it will automatically add Content-Type header to the list of headers. There you can change it to whatever you want. 

The dropdown list was a shortcut for adding content-type header but it caused too much confusion. Therefore it was removed and it will not coming back to the app.
