### ISSUE TITLE
Chrome v45: fetch API: URL scheme "chrome-extension" is not supported.

### ISSUE THREAD

**Issue by jarrodek** [jarrodek/ChromeRestClient#348]
Fetch API cannot load chrome-extension://dgdnbknnbbacmakijmkdbhhopogfofkh/assets/definitions.json. URL scheme "chrome-extension" is not supported.

**Comment by jarrodek** [comment]
The same in version 44.

**Comment by jarrodek** [comment]
Changed because minimal supported version for the ARC is 45.

**Comment by jarrodek** [comment]
The same in 46.

**Comment by jarrodek** [comment]
The fix will be available in next update.

**Comment by jrusse12** [comment]
When should I hope to see the next update? Will the update allow a user (myself) to use Advanced Rest Client with Chrome version 35.0.1916.153 m? I was able to use your program just a few months back before the latest updates? If the update won't fix that issue is it possible for me add the old extension program you had before? 
Unfortunately my hands are tied as to just upgrading to the latest versions of Chrome because my works security disables that feature. I maybe able to upgrade to version 42 but not sure if I'll be able to upgrade any higher.

**Comment by jarrodek** [comment]
Fetch API is enabled in Chrome 42. 
Anyway the app itself should work anyway. It has couple of references to `fetch` API but only in less important function (like analytics, requests to app's server). You may see this error but it's not influence to main purpose of the app. If it is not working it is a different reason.
