### ISSUE TITLE
[enhancement] ability to import/export project to google drive

### ISSUE THREAD

**Issue by justinhelmer** [jarrodek/ChromeRestClient#356]
The google drive feature is so juicy. Unfortunately we are always adding and removing endpoints.

So far as I can tell, endpoints must be imported/exported individually, which is not sustainable in our current model. 

We result to doing file dumps on an interval. Which works great.

**Comment by jarrodek** [comment]
I'm planning to redesign collaboration features in the app. It's one of key features I'd like to develop this year. I'm aware of a need and thanks for reminding it.
I'd like to focus on 3 ways of colaboration:
1) Offline (file) import / export  - it's already in the app
2) Drive integration - now you can import / export single item from Drive but i'd like to have a possibility to sync project data with drive as well. So when one person save a new version on drive other people will receive a notification that there's a new version of the file available on Drive. It should help teams to collaborate.
3) Server sync - similar to Drive pattern but it will not use Google Drive (for people / companies that have strict data protection policy). 
Right now I can't declare any particular timing for it because last week my whole roadmap crashed after I discovered that Google is planning to drop support for legacy apps (ARC is one of them) so right now all available resources are moved to upgrade the app to the new apps.

Thanks for issue report. This one is quite important to me.

**Comment by justinhelmer** [comment]
completely understood. Thanks for the insight

**Comment by jarrodek** [comment]
Import / export of arc data (all data) from / to Google Drive is already implemented.
