### ISSUE TITLE
Saved requests does not honor headers that have been modified by copy-pasting

### ISSUE THREAD

**Issue by imochurad** [jarrodek/ChromeRestClient#365]

**Comment by jarrodek** [comment]
There may be an issue in CodeMirror but I'm not sure yet. 
I tried two cases:
1) When you ctrl+s the request when pasting headers and not leaving the headers field. This test **failed**. 
2) When you ctrl+s the request when the input field loose focus. This test **succeeded**.

I'm assuming that the problem is in "raw" tab (since you can't paste data into the form - which btw would be nice improvement). So the changes are not propagated in the app because CodeMirror haven't fired a change event. I have to test it first.

Thanks for your issue report.

**Comment by asalazar-pley** [comment]
To me, it is not only the headers, but also the body, whatever is the last request is what stays sort of in memory behind the scenes regardless of modification to headers or body.
Have to kill the app and restart and hopefully it will work.
This has been a bug introduced quite recently, about 1 month or 2 ago, it was working well for the longest time.
