### ISSUE TITLE
Projects created in incognito lost on closing browser

### ISSUE THREAD

**Issue by appningsdev** [jarrodek/ChromeRestClient#366]
When we create a project and save it while in chrome's incognito window it works fine until u close that incognito session. 
Not able to find that project anywhere i think its removed as a part of app data. 
I have 2 questions.
1. Did any one experience this ?
2. Is this fixable ?

**Comment by jarrodek** [comment]
Chrome incognito mode won't allow to persist any data. When you close incognito window all data created during this session will be deleted from the app. That's why it is called `incognito`.
Answering:
1. All the people who tried this 
2. Not sure what do you mean

Anyway there's no possibility to store data in database / localStorage / chrome API storage during incognito session. It's as base of incognito feature.

**Comment by appningsdev** [comment]
Ok Thanks.
