### ISSUE TITLE
No option to set the content type in this updated version

### ISSUE THREAD

**Issue by subbuvidyasekar** [jarrodek/ChromeRestClient#368]
Hi friends,

I have used this Rest Client of 2 months.
Last week, after the update, i didnt find place to change the Content Type. Older versions had that option below the Payload tab. now its missing.

![rest](https://cloud.githubusercontent.com/assets/2427395/12443974/ecdc0d38-bf81-11e5-9827-1bf5de218652.png)

**Comment by yaroslav-kovalchyk** [comment]
You have to type it by hands now.

**Comment by subbuvidyasekar** [comment]
Thanks my friend..

can you please give sample for the same..

**Comment by yaroslav-kovalchyk** [comment]
Here is it:
![content_type_in_rest_client](https://cloud.githubusercontent.com/assets/9320045/12445511/3bc0fafe-bf6d-11e5-8ae3-524e3de21bb0.png)

**Comment by getmeben** [comment]
It doesn't keep the content type value after a ; though - try putting 

Content-Type: application/json;charset=UTF-8

Anything after the ; is dropped silently by this new version, was never a problem previously.

**Comment by jarrodek** [comment]
When you switch to the method that carry a payload a default C-T header will be put in the headers field. You have autofill and suggestions. Basically its even faster than earlier.
See http://restforchrome.blogspot.co.uk/2016/01/encoding-drop-down-removal-from-app.html for more explanations. 
So in this matter the issue is invalid. However @getmeben mentioned that there's an issue with headers and ";" character. I tried to reproduce the problem but I couldn't. The app works as expected. Can you give me more details?

**Comment by getmeben** [comment]
The truncation after ; is fixed if you turn off codemirror it seems...

**Comment by jarrodek** [comment]
I'll see what I can do. It's basically the same value and there's no transformation between CodeMirror and regular text. I have to check if there's an issue with the CodeMirror.
