### ISSUE TITLE
Unknown error - background page commuication?

### ISSUE THREAD

**Issue by amirNatx** [jarrodek/ChromeRestClient#374]
I tried to POST a messgae using the Advanced Rest Client for Chrome but continue to get this error. Has anyone seen this error before and can you tell me what it means? 

![capture](https://cloud.githubusercontent.com/assets/7967309/12691330/d863123c-c69f-11e5-8084-c976c56e5bb6.PNG)
![capture](https://cloud.githubusercontent.com/assets/7967309/12691336/e134c612-c69f-11e5-9e04-46232f80dd0f.PNG)

**Comment by jarrodek** [comment]
It means that you either use dev version of the app or there were an error in the background page caused by old Chrome version (it use syntax available from Chrome 45+).
You'll get rid of the error when you upgrade Chrome. You can be sure when you check chrome://extensions page and inspect background page for the app.

**Comment by amirNatx** [comment]
I'm using an old version of Chrome (Version 41) on my work laptop, so this
could very well be the issue. Thanks for the reply, I appreciate it!

**Comment by jarrodek** [comment]
Definitely it's caused by it since JavaScript classes that has been used in the background page has been introduced in Chrome in version  45. Background page is not initialising due syntax error and communication with it ends with this error.
Can you upgrade Chrome to new version?

**Comment by amirNatx** [comment]
I'll have to get it approved through my IT department. I found an alternative on Firefox in the mean time. Thank you so much for clarifying the issue!

Regards,
Amir
