### ISSUE TITLE
add JSON tab by default and add setting to choose prefered tab to show response

### ISSUE THREAD

**Issue by TheRealMilagro** [jarrodek/ChromeRestClient#388]
Hi, great extension.
I do not understand why JSON tab is not shown by default? JSON tab display is much prettier.
So i am missing a setting to add JSON tab by default and a setting to choose prefered tab to show the response. Would be very useful imho.
Thx, Milagro

**Comment by jarrodek** [comment]
It's because not all APIs use JSON :) 
But I'm not sure if I follow you here. When the app detects JSON content (based on content-type header) it will open JSON tab as a default view. If you don't see JSON tab opened by default but any other tab it means that the server responded with wrong content-type header.

Because HTTP spec allows omit content-type header and then client should try to guess CT based on payload I will not close this ticket. In a future I'd like to have CT guessing base on payload in the app.

**Comment by TheRealMilagro** [comment]
Thank you Pawel,
sorry, i missed that. I corrected my restservice to send correct 
Content-Type:application/json and this makes it shown-up in JSON-tab by 
default.

Thanks and Regards,
Bernd

Am 15.02.2016 um 17:56 schrieb Paweł Psztyć:

**Comment by jarrodek** [comment]
In summary, add payload based content-type detection and open tab depending on detected CT.

**Comment by jarrodek** [comment]
It is related to #306

**Comment by jarrodek** [comment]
This is fixed already.
