### ISSUE TITLE
New version of ARC doesn't set or uses cookies set inside Chrome

### ISSUE THREAD

**Issue by maxtepkeev** [jarrodek/ChromeRestClient#435]
Hi,

I'm using a session based API in one of the projects. After upgrading to the latest version I can't make API calls anymore because new versions of ARC doesn't set user's session cookie after I call an API's login endpoint which sets cookie, i.e. new version of ARC sends set-cookie header but the cookie is not actually set.

Versions:
ARC: 6.1.10.93
Chrome: 49.0.2623.110

**Comment by jarrodek** [comment]
Thank you for an issue report.

I can actually write a module that will handle cookies session. But it will take some time. Right now I can  only suggest to to copy 'Set-Cookie' header value returned by your server and use it in 'Cookie' header when making a request.

**Comment by jarrodek** [comment]
On the other hand there may be a second transport adapter in the app that uses XHR or Fetch transport and the users may choose in settings which transport they want to use. For more "browser" based request they may switch to other transport method and send browser's default headers wit the request.

**Comment by warrenrumak** [comment]
This really needs to be addressed, and soon.  ARC is now very frustrating to use for a lot of people who are developing web APIs with a cookie-based authentication layer.  Kind of surprised this use case was missed during development of the new version.

**Comment by davemorrissey** [comment]
For those looking for an alternative, DHC Rest Client uses cookies.

**Comment by jarrodek** [comment]
The app will not use cookies set in Chrome. However it uses it's own session management. It accepts and stores cookies like other user client does and sends them automatically with the request that matches domain and path as defined in the spec.

**Comment by davemorrissey** [comment]
The use case I have is calling App Engine cron jobs that are restricted to the administrator role. Google say this: "To test a cron job, sign in as an administrator and visit the URL of the handler in your browser". Our endpoints mostly use POST instead of GET.

When ARC was embedded within Chrome and shared Chrome's cookies this was easy, simply sign in as an admin in one tab then make the request in ARC in another. With ARC now a separate application it can't be done.

I've moved to another plugin now and I guess this is a relatively unusual use case.
