### ISSUE TITLE
GET Services throwing Error

### ISSUE THREAD

**Issue by JananiSanthanam** [jarrodek/ChromeRestClient#452]
All the REST GET services are throwing error from the input headers copied to the output with error saying as null

How to get the REST console tabbed into the chrome. Did not like the feel of opening a seperate Application. Not able to duplicate the REST client and harder to switch. Performance issues.

## Expected outcome
What should happen?
GET services should give proper response.
## Actual outcome
What happened?

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

## Steps to reproduce
1.  Call any GET Service with headers
2. 
3.

**Comment by jarrodek** [comment]
Can you share what headers you are putting into the request? And what's the actuall response?

**Comment by JananiSanthanam** [comment]
Headers are below:

WM_SVC.NAME: order-service
WM_QOS.CORRELATION_ID: 100
WM_SVC.VERSION: 2.0.0
WM_SVC.ENV: stg
WM_CONSUMER.ID: 9cc5a286-c674-4641-bd0d-05bd7275f8ad

and the Response says:


<?xml version="1.0" encoding="UTF-8"
standalone="yes"?><ServiceResponse><status>BAD_REQUEST</status><errors><error><code>400</code><field>WM_QOS.CORRELATION_ID</field><description>WM_QOS.CORRELATION_ID
set blank or null</description><info>WM_QOS.CORRELATION_ID set blank or
null</info><severity>ERROR</severity><category>REQUEST</category><errorIdentifiers/></error><error><code>400</code><field>WM_SVC.ENV</field><description>WM_SVC.ENV
set blank or null</description><info>WM_SVC.ENV set blank or
null</info><severity>ERROR</severity><category>REQUEST</category><errorIdentifiers/></error><error><code>400</code><field>WM_SVC.VERSION</field><description>WM_SVC.VERSION
set blank or null</description><info>WM_SVC.VERSION set blank or
null</info><severity>ERROR</severity><category>REQUEST</category><errorIdentifiers/></error><error><code>400</code><field>
WM_SVC.NAME</field><description>WM_SVC.NAME set blank or
null</description><info>WM_SVC.NAME set blank or
null</info><severity>ERROR</severity><category>REQUEST</category><errorIdentifiers/></error><error><code>400</code><field>
WM_CONSUMER.ID</field><description>WM_CONSUMER.ID set blank or
null</description><info>WM_CONSUMER.ID set blank or
null</info><severity>ERROR</severity><category>REQUEST</category><errorIdentifiers/></error></errors></ServiceResponse>

**Comment by jarrodek** [comment]
So I understand that the issue is that the server do not see the `WM_QOS.CORRELATION_ID` header as it was not set?

**Comment by JananiSanthanam** [comment]
AS you see below the headers WM_QOS.CORRELATION_ID is passed. I am not sure
where you are looking at? The same service is working from the Old ARC
before upgrade.
Is there some way i can go back to the old one. Because the new one is not
stable. Moving from one Request to other it not coming the Service details.

Could you please release a more stable version.


WM_SVC.NAME <http://wm_svc.name/>: order-service
*WM_QOS.CORRELATION_ID: 100*
WM_SVC.VERSION: 2.0.0
WM_SVC.ENV: stg
WM_CONSUMER.ID <http://wm_consumer.id/>:
9cc5a286-c674-4641-bd0d-05bd7275f8ad

**Comment by jarrodek** [comment]
Because I can't understand where's the issue here I'm asking another questions to clarify :)

So the steps to reproduce are:
1. Create the request with headers provided above
2. Send GET request to the endpoint

And the expected output is that the server sees the headers provided in the request form where actual output is that the WM_QOS.CORRELATION_ID: 100 (at least) header is not sent to the server.

Is that correct? Since I don't know your API implementation I can only guess what is happening.

**Comment by jarrodek** [comment]
Is the issue might be caused by case sensitivity? I mean is your endpoint recognizes letters cases for headers?

I tried this quick request:
![image](https://cloud.githubusercontent.com/assets/3320020/14435803/859d0d90-0011-11e6-8ee3-49c9c6f5d815.png)

Selected headers are request headers and they were sent (according to the HTTP spec at least) correctly. But if your server do not recognize case sensitive for request headers it may lead to this issue.
Can you confirm that?

**Comment by JananiSanthanam** [comment]
The Same Headers is working in the old Advanced Rest client and it is
giving success response. Because few of my co-workers still have the old
version tried in that.

Not just this GET Request. Most of the GET request are having this issue.

The servers recognize case sensitive .


Thanks,

**Comment by jarrodek** [comment]
According to spec the headers are case insensitive and both client and a server should recognize this. See http://stackoverflow.com/a/5259004/1127848 for the discussion.

Previous transport in ARC was based on XHR object. Current one is based on sockets. However it is using standard Headers JavaScript object to carry the headers. Headers are altered by this object just before they are send. If you believe this is wrong you may file an issue report in https://crbug.com/ which is an issue tracker for Chrome.

Anyway I strongly suggest to adjust your server side code and follow the HTTP spec. Issue with the ARC app can be only a beginning or list of serious issues in future with clients (any HTTP clients either on server or client side). I believe that the app just pointed that out.

For now I'm not considering changes in code since its follows HTTP spec.
