### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by kbss** [jarrodek/ChromeRestClient#456]
Your description here

## Expected outcome
Successful request

## Actual outcome
ERR_CERT_AUTHORITY_INVALID

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.110
Platform: Windows (7)

**Comment by geeprime** [comment]
Self-signed or otherwise untrusted authorities do not work in the latest version. There seems to be no way to allow untrusted certificates to work. I can import a trusted authority, but it would become frustrating to trust each individual server. Can we get a mechanism to allow self-signed certificates, without having to import into the OS keystore?

**Comment by geeprime** [comment]
Looks to be a duplicate of 432, and there is a thorough discussion on that and a couple of other linked defects.

**Comment by kbss** [comment]
Duplicate, closed
[https://github.com/jarrodek/ChromeRestClient/issues/432](https://github.com/jarrodek/ChromeRestClient/issues/432)
