### ISSUE TITLE
The status provided (618) is outside range [200,599]

### ISSUE THREAD

**Issue by anonimoaveces** [jarrodek/ChromeRestClient#457]
Hi, I'm currently working on a REST API, which when it fails in some occasions, it responds with a custom HTTP STATUS CODE from 600 to 699.

## Expected outcome
HTTP Status Code: 618
JSON response: 
{
  "Error": "blablabla",
  "Module": "blahblahblah"
}

## Actual outcome
After last update of Chrome Plugin when I receive a custom HTTP Status Code. ARC shows:

The status provided (618) is outside range [200,599] with a dead emoji (x-x)

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.110
Platform: Windows (8.1)

## Steps to reproduce
1. Build a mock REST API SERVER which response with a custom http status code, e.g. 618

I would like (at least) through configuration allow receive any http status codes

Thanks.

**Comment by jarrodek** [comment]
That's the tough one.
The app uses Fetch interface (and it's Request and Response objects). When creating a response it invokes Response constructor which is throwing an error when the status code is outside the range.
So your question actually is if the app should abandon web standards and allow users for custom HTTP constructions. While it is not a very big problem for app to do this is a problem with the standards. Remember that you programming this API is responsible for it to work. While you are testing the API in ARC it may seems to work (assuming that the change will be implemented in the app) it will not work in real world because transports like Fech will throw an error.
The sole purpose of the app is to allow developers to test if their APIs are working and to help debug it if not. Now, allowing you to read the response without the error will defeat the purpose of the app because it will work in the app but when you finish your API it won't work in clients. 

I'm open to debate this but right now I'm against this idea and the app should stick to web standards and promote good practices for RESTful services.

**Comment by anonimoaveces** [comment]
Hi, thanks for your quick response.

I don't agree with your statement, but it's your product and you manage how to wrap the http responses.

I will use other plugins to test my API anyway.

P.S. Close this issue asap.

**Comment by jarrodek** [comment]
There may be more people to join the discussion because it's a serious subject.

**Comment by jarrodek** [comment]
This issue was resolved in last release.
This error should not be present event if the response is errored.
