### ISSUE TITLE
Self-signed SSL certificates cause net::ERR_CERT_DATE_INVALID error

### ISSUE THREAD

**Issue by bigunyak** [jarrodek/ChromeRestClient#475]
Your description here
Requests fail against a service with self-signed SSL certificate.

## Expected outcome
Should just work as it did before.

## Actual outcome
Get the following error:
"
There was an error during the request
net::ERR_CERT_DATE_INVALID
"

## Versions
App: 6.19.17.118-stable
Chrome: 49.0.2623.87
Platform: Linux (-)

## Steps to reproduce
1. Try to send a request to a service with self-signed certificate.
2. 
3.

**Comment by zckrs** [comment]
Same issue. 

How can I find the old version ?

**Comment by jarrodek** [comment]
There's no point of installing old app since old architecture is deprecated and soon will be removed. 

The app can't do nothing with this error (or I'm not yet aware of the solution). Chrome itself can ignore certificates errors but it doesn't allow apps to do it. I've filed a [chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=603104) but I'm not sure if they actually do something about it. 
I will however continue to explore possibilities.

**Comment by bigunyak** [comment]
Well, everything worked just fine in the previous version.
What's the point in all these new features and goodies if normal simple requests don't work.
I'm sorry to say, but it's useless in that case.

**Comment by zckrs** [comment]
Sorry @jarrodek I used ARC instead of Postman because extension go in tabs and not in new window.

And now request in dev env with SSL self signed stop to work and I can't see my request in chrome debugger (but I see the X request to google analytic)

**Comment by jarrodek** [comment]
It is "useless" when the certificate is invalid. Which makes developing and testing restful services more complicated. But on the other hand eventually you will need a valid certificate to use your API in production. Or you can just generate own self-signed certificate and the it will work.

**Comment by jarrodek** [comment]
All, please see discussion at https://bugs.chromium.org/p/chromium/issues/detail?id=603104

The issue is with the certificate and not with the app. Therefore WAI.

**Comment by zckrs** [comment]
I switch to http://www.getpostman.com/

Thank you for your response.
