### ISSUE TITLE
Get Request Gives 400 BAD Request error response saying all the headers are NULL

### ISSUE THREAD

**Issue by atul05kumar** [jarrodek/ChromeRestClient#484]
Your description here

## Expected outcome
Its should give the 200 OK, and response of the service.

## Actual outcome
It gave a 400 : Bad Request. Saying that all the headers are NULL. However Headers are given properly.

## Versions
App: 6.15.15.114-stable
Chrome: 49.0.2623.112
Platform: Mac OS X (10_10_5)

## Steps to reproduce
1. Form GET request.
2. Give proper headers.
3. See the response.

**Comment by jarrodek** [comment]
Is this can be related to #453 and #480?

**Comment by atul05kumar** [comment]
@jarrodek This issue started coming up, after this new update where you made it an independent app, earlier the header were going through. #453 and #480 are different. In my case, the response xml says that all the headers passed were NULL.

**Comment by jarrodek** [comment]
Referenced issues are about case sensitivity of headers. If server code do not handle headers correctly it's a server code issue, not the app's. According to the HTTP spec headers are case insensitive and both client and server must handle this correctly. 
Giving your description I can assume that it is the case.

**Comment by atul05kumar** [comment]
@jarrodek As i said in my previous comment, that this issue started coming up only after the update. I ran a saved request which was there before update, This eliminates the possibility of me accidentally modifying the header. Secondly the same request gave 200 OK in another rest client POSTMAN eliminating the possibility of problem with server code.

**Comment by jarrodek** [comment]
Not necessarily. New version uses JavaScript build-in Headers object. Previous did not. This object transforms headers to lower case.
When previous version (like Postman) used XHR object it may worked well. However it case sensitivity is a case here you can't expect that you're code will work everywhere since it's inconsistent with HTTP spec and transport method has nothing to do with it. 
So please, check on your server if your code handle headers correctly or is it something different. As for now I can't reproduce the issue and the transport pases tests.

**Comment by jarrodek** [comment]
Can author of the issue report can confirm that the issue is or not related to the headers insensitivity?

**Comment by jarrodek** [comment]
I'm closing it because of lack of activity.
