### ISSUE TITLE
Not able to send api request when on proxy

### ISSUE THREAD

**Issue by shashwatbhatt** [jarrodek/ChromeRestClient#515]
If you are behind a proxy and when you send a request to remote server the request by default always times out.

## Expected outcome
I should be able to send the request to remote servers when I am behind a proxy

## Actual outcome
What happened?
Request timeout

## Versions
App: 7.7.26.168-stable
Chrome: 48.0.2564.116
Platform: Linux (-)

## Steps to reproduce
1. Start Rest client and with proxy
2. try sending any request to a remote server

**Comment by jarrodek** [comment]
Please, setup proxy in Chrome settings. If the problem persists file an issue report in Chromium project (crbug.com).
I'd incline to close it as author of the app can't change proxy settings.

**Comment by girtsn** [comment]
confirmed same issue here. it does not use the proxy of chrome in windows (coming from windows internet settings in turn). postman still works so it IS an issue with this plugin. you have like 7 open bugs all related to timeouts doing requests, 99% sure they are all related to proxy not being used thus not resolving hostnames and thus timing out. inclined to close all of the bugs? suggest to fix them instead.

**Comment by jarrodek** [comment]
@girtsn thanks for joining discussion.
I tried using XHR as a transport instead of sockets. Without success. It has the same issue. It's more about networking in packaged apps in overall than particular implementation.
I'm trying to figure it out how to setup proxy differently but as for now setting up proxy settings in Chrome settings is an only way to do it.
