### ISSUE TITLE
sees no authorization header

### ISSUE THREAD

**Issue by sanekesv** [jarrodek/ChromeRestClient#517]
When I send GET request with an authorization header me the answer comes, that the request is not it.
https://i.gyazo.com/6369010f7673080484ae7975386e76a2.png
"message": "The request Unknown Authorization header"

**Comment by JonathanNet** [comment]
I got the same error, after update to the new version :(

**Comment by jarrodek** [comment]
Probably it is an issue related to #491.
If your server's code not handling headers' case insensitivity is a case then I'd be inclined to close it as WAI.

**Comment by jarrodek** [comment]
Just to clarify - headers are set properly as you shown in the screenshot. The "source" message is generated string of headers part of the HTTP message and this particular string was send to the server. Since `Authorization` header is included  in the request and have proper value there's everything OK with the app.

**Comment by primox** [comment]
With new version Authorization header is send as: "authorization: xxx" unlike in previous versions were it was sent as "Authorization: xxx" (notice upper case A). 

This broke ARC on my app. Will probably fix app to be case insensitive, but please don't change it without any reason?

**Comment by sanekesv** [comment]
jarrodek, yesterday everything was working until a new version ARC

**Comment by jarrodek** [comment]
As in referenced issue #491 - HTTP headers are **case insensitive**. And this is defined in spec. If you proceed with invalid server code you are risking that the app will broke in production. It will be definitely broken in service workers which uses Fetch API. And the Fetch API uses Headers object (JavaScript built-in object) that ARC uses to transport headers. And the only issue with the app would that it didn't report an issue earlier - which is the sole purpose of the app.

I don't see creating custom objects (instead of using build in JavaScript objects) just to make the app works with potentially invalid server code and against HTTP spec. If you guys think it may be an error you should file an issue report in both W3C spec for Fetch's Headers object and Chrome issue for Headers implementation.

**Comment by CaryLandholt** [comment]
Would be much more appreciated to provide a warning for a period of time about case insensitivity, allowing developers an opportunity to **fix** their server-side code before ARC stops working altogether.  Pretty heavy-handed approach.

ARC has been an invaluable tool, but right now is completely unusable.

Again, recommend the deprecation warning approach.  Warn in advance of an upcoming breaking or _potentially_ breaking change.  After that period of time, make the change.

**Comment by jarrodek** [comment]
@CaryLandholt thanks for the comment.

I can't know that there is a difference in headers. The app gets values from the text field and puts it directly to the Headers object (it's a build in JavaScript object to handle HTTP headers). Just before passing it to the socket they are retrieved from this object as string. The app is doing nothing with them. Just passing to the socket (which is a separate library). If Chromium team decided that the headers can be transformed I can't do much about it. To present the issue checkout this gist that I prepared to demonstrate the issue: https://gist.github.com/jarrodek/29491a10727ea65d999e56eefc768229#file-headers-test-js

Summarizing: I can't warn before sending a headers about letter case because I basically technically can't and I don't know what was intention of the user (to be lower or upper case). However from HTTP spec POV there's no difference so the app should not care about it.

**Comment by CaryLandholt** [comment]
Thanks for the feedback and awesome product.  I don't believe I was clear enough - I was thinking a warning/deprecation notice in the docs/release notes.

Thanks again!

**Comment by sanekesv** [comment]
The program does not meet my requirements after the release of the new version.
I would look for alternatives.
Very sad.
Thank you for your quick answers

**Comment by pubudu91** [comment]
If the app isn't treating header field names as case insensitive, then that particular app isn't conforming to the HTTP spec. But I don't see how this applies to the RESTClient though. The REST Client is meant to be a developer tool right? As such, shouldn't it give the developer the full control over the requests sent through it? That flexibility is lost when the tool automatically changes the field names to lower-case. 

Take the very same scenario you mentioned. If an app conforms to the HTTP spec, it should not consider case sensitivity of the header field names. Now suppose you want to test whether your app conforms to this particular point of the spec using the REST Client. With the new update, how are you gonna do that, when the Client converts the header names to lower case anyways? 

I loved this extension, but had to switch to Postman because of this issue.

**Comment by jarrodek** [comment]
@pubudu91 Please, read my previous comment.
The app is not changing headers. Build in JavaScript object does (Headers). I don't have control over this object and since it complies with the HTTP spec I'm not going to change that behaviour.

Furthermore as a developer tool it should report an error where it can because if you publish your service and it won't work with clients you'll send another issue report claiming that the app should have been report an error that it may not work (which obviously can't do it because don't know how's the server side code is implemented). I don't see how this is helpful.
