### ISSUE TITLE
Issue in New Rest Client - with "&' character

### ISSUE THREAD

**Issue by Meenakshiithape** [jarrodek/ChromeRestClient#524]
I have an issue in passing the & character in parameter value.
Suppose I want to pass the parameter description which contains "&" character then it only accepts the characters before "&"
for eg,
if parameter "description" having value "Items contains the code & data" then it just display the value for description as "Items contains the code" is return response

**Comment by jarrodek** [comment]
Hi,

Thanks for an issue report.
Can you please clarify if you are talking about URL params or payload? And that's the content type if the request.

Finally please, paste "source message" section from the response panel > Request headers tab.

Thanks

**Comment by Meenakshiithape** [comment]
Hi,
I am passing the parameter in POST data not in url.
Post parameter is "itemInfo" and value is "Items contains the code & data".
Return response just return the "Items contains the code"

When I click on Raw payload tab and again on Data form then its show two parameters, inteminfo and data
"intemInfo" : Items contains the code
"data:


![post_api_rest](https://cloud.githubusercontent.com/assets/2040142/14671514/c322ee50-070f-11e6-961c-e7d035bb81e2.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for clarification.
The problem here is that the request is not url-encoded. You can read more about it in [the spec](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1).

There are two buttons in the payload editor. You can use "encode" button to easily encode the payload.

I'd close the issue as WAI but it may be an usability issue in presenting the information about invalid input.

**Comment by jarrodek** [comment]
Appropriate buttons has bee added to the UI.
