### ISSUE TITLE
POST PUT JSON problem with &

### ISSUE THREAD

**Issue by DanRamGim** [jarrodek/ChromeRestClient#548]
Sending a POST or PUT with JSON with Content-Type: application/x-www-form-urlencoded, 
if you send something with "&" in it, the JSON is CUT exactly where the "&" is.

## Expected outcome
What should happen?
receive a JSON like THIS.
{"Title":"Este es un b&ug realizado por Intelisis ","Bug_Situation":"New","Bug_Type":"Sí","Clave_Cliente":"4321"}

## Actual outcome
What happened?
I receive this half JSON
{"Title":"Este es un b

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (8)

## Steps to reproduce
1. Select a web service that receives a JSON
2. select POST
3. write Content-Type: application/x-www-form-urlencoded
4. write your JSON with a "&" between a value

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. 
You should encode payload before sending it to the server. You have special button for that when you set up 'application/x-www-form-urlencoded' content type. 
If you do not do it the server will think that the `&` means new param definition.

The app itself can't do it by you because It does not know what's your intention and the base rule is to not change request if not necessary. 

As per my response I'd inclined to close as WAI.
