### ISSUE TITLE
An error during the request  net::ERR_NAME_NOT_RESOLVED Error 

### ISSUE THREAD

**Issue by einatl** [jarrodek/ChromeRestClient#569]
HI,
I've updated the version of the Advanced Rest Client and since then the the majority of the requests I send get this error:

"There was an error during the request

net::ERR_NAME_NOT_RESOLVED"

I used the same requests in the past before the update and they worked fine. Furthermore, these requests do work once in a while in the new version.
What's the reason of this error? How can I fix this?

Thanks!

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.

Is there a proxy involved in the request?

**Comment by einatl** [comment]
No proxy, but maybe I was connected to VPN (if this matters)

**Comment by jarrodek** [comment]
Thank you for clarification.
The error is reported when the socket connection can't established with the remote machine. As an author I can't do much about it. I have only socket I'm operating on. This error means either you're offline, server's offline or Chrome networking system can't find a host in your network configuration. It can be caused by Proxy for example. VPN connection is a proxied connection so it may be causing the error. You can change proxy settings in Chrome settings or file a Chrome bug. I can't do much more about it.

**Comment by einatl** [comment]
Using the Postman it did work…
