### ISSUE TITLE
cookie issue

### ISSUE THREAD

**Issue by oak-tree** [jarrodek/ChromeRestClient#586]
Just upgrade to the new version. NICE LOOK! 
But it seems it does not save and use cookies for the same domain. Any ideas how to overcome this issue?

**Comment by jarrodek** [comment]
Hi,

Thanks for issue report.

The solution is in the hotfix branch. However there will be no session information exchange between the app and Chrome since there's no API available for apps to do this. The app will be able to read cookies from the response and set them back in next request to the same server (as browsers does).

As per this I'll close this issue.
