### ISSUE TITLE
Useful resize capability is gone

### ISSUE THREAD

**Issue by cpoblete** [jarrodek/ChromeRestClient#595]
In the previous version, the entire view could be resized using the browser ctrl+ or ctrl-. This is very useful viewing in a large display or small display. Request to have resize capability in the latest version.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Unfortunately Chrome apps don't have much of web browsing experience from chrome. There are just no such commands and because Chrome apps suppose to behave more like native apps - not web apps - I'm not planning copying this functionalities in future.

However, roadmap includes theming where there will be some "compact" theme. It may help you on different screens.

As per my comment I'll close this issue as wontfix/WAI.

**Comment by cpoblete** [comment]
It's a limitation. I'll watch the theming.
