### ISSUE TITLE
Properly secured but not useful when debugging

### ISSUE THREAD

**Issue by cpoblete** [jarrodek/ChromeRestClient#596]
I see a lot of improvement in security and gives me a lot of useful information about certificate errors. I like that. However, it has become unusable to me when I use this app for debugging a REST service with certificate not properly configured. I'd like to request a similar option in the chrome browser where you are able to "proceed (unsafe)" when there is certificate problems and continue with the transaction.

**Comment by jarrodek** [comment]
Hi,

Thank you for your thoughts. 
Please refer to the discussion in crbug (https://bugs.chromium.org/p/chromium/issues/detail?id=603104) where I discussed this issue with Chromium team.

As per referenced discussion I'd be inclined to close this issue as wontfix/wai.

**Comment by cpoblete** [comment]
Another REST app that is running as an "app" does not have this issue. This app has been helpful and a preference to me for more than a year now, this issue is preventing me to continue using this app. I will come back to this app once this issue is fixed. Thanks.

**Comment by jarrodek** [comment]
@cpoblete if the certificate error is caused by self-signed certificate, you can install it in chrome settings and the app will work as usual.
Any other error means that the certificate is invalid. According to my discussion with Chromium team there will be no fix for apps to allow them to accept invalid certificates. If this is possible you should install valid certificate on your dev server (either self-signed or from free services like letsencrypt.org)

**Comment by jarrodek** [comment]
It is fixed by https://github.com/jarrodek/ChromeRestClient/commit/89973b258fe80f0bcc33814111917d6ef272617c

**Comment by cpoblete** [comment]
I see the fix. Thanks!
