### ISSUE TITLE
Lots of good features are now missing from the new rest client

### ISSUE THREAD

**Issue by nitecoder** [jarrodek/ChromeRestClient#600]
Making the client go into its own window looks good at first but many features are now missing. Please bring them back! Simple and critical usability things, like:
* ability to search in the output (used to be for free with Cmd+F browser function)
* ability to open multiple windows (used to be for free as well)

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Mac OS X (10_9_5)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.

The search functionality is available in the app:
![image](https://cloud.githubusercontent.com/assets/3320020/14764170/7b67771a-09ae-11e6-98d0-a7cd4f12cb9c.png)

However right now there is an issue with cmd+F combination. It is working for ctrl+f. It is fixed in hotfix branch so expect update in coming days.

You can open more windows using a button in left nav column > bottom icons > more > open new window. However it gave me an idea that it should open new window on ctrl/cmd+N shortcut. So I wont't close this issue just yet.

**Comment by nitecoder** [comment]
Awesome! Thanks very much for the reply.

Yes, Ctrl+F does work! Also found the new window functionality. Cool. My 
usual way of opening new windows was actually using Cmd+T for a new tab. 
Might be helpful to support that shortcut as well? Or at least include 
into the tutorial.

Thanks again!

-Dmitry

**Comment by jarrodek** [comment]
I actually added ctrl/command+n for that. It seems more natural to use it
for new window.
Also I'm not excluding that someday tabs will be in the app and I don't
want to mix things up.
I think in this case it should stay as is.

**Comment by nitecoder** [comment]
Thanks, that makes sense.

One more thing - what is the caching situation with the new client?

Before, Chrome had always applied its very aggressive caching and 
wouldn't even call the server if arguments didn't change. After a bunch 
of digging I found a solution that worked for me - Cache Killer add-on. 
What is the situation with the new client? Can caching behavior be 
controlled better? If not, does Cache Killer still work? How do I enable 
/ install it? Or does it just work Chrome-wide?

Thanks!

-Dmitry
