### ISSUE TITLE
Ability to set proxy?

### ISSUE THREAD

**Issue by mm-gmbd** [jarrodek/ChromeRestClient#602]
It doesn't look like ARC utilizes the system's proxy settings. An ability to manually configure the proxy settings that ARC uses (or, just a checkbox that enables using the system proxy settings) would be very useful.

## Expected outcome
Make REST requests behind a proxy.

## Actual outcome
All requests time out.

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. Make a request (OK).
2. Switch to corporate proxy.
3. Make a request (FAIL).

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. 
The app can't actually control proxy settings. Like old one. Instead, the old types of apps could use the same network settings as the browser tabs. For unknown reasons (for me at least) Chromium team decided that the new apps (based on new architecture) will not share this settings. 
You can however setup proxy in Chrome settings (chrome://settings > Show advanced settings... > Network).
If - after setting things up - there are still problems with networking you can try debug proxy in chrome: https://www.chromium.org/developers/design-documents/network-stack/debugging-net-proxy

I just want to note as an author of the app that I couldn't not upgrade the app to new architecture because old one was deprecated and CWS already removed old types of apps. Also, because of the lack of documentation on that matter in Chrome API documentation, I couldn't predict any proxy problems. It came up after the release.

As per my response and lack of any other options here I have to set this issue as a wontfix.

Thanks

**Comment by mm-gmbd** [comment]
Apologies for not responding before, and thanks for the feedback. Understood on the reasons for the wonfix and the close -- thanks for considering!

**Comment by jarrodek** [comment]
Actually, in beta channel there is an update that may help. 
I've created a proxy extension for making a XHR connections from Chrome - not the app. It's in the main UI so you won't miss it. You'll need to install additional extension thought. 
When I test it I'll release it in stable channel.
