### ISSUE TITLE
URL's with spaces no longer converted, return 400 bad request

### ISSUE THREAD

**Issue by ependergrass** [jarrodek/ChromeRestClient#619]
Before the major update, all of my saved test data worked great - including spaces, single quotes, etc. Not they produce a 400 bad request from the server. If I enter them into chrome itself, it converts the characters and I can use that URL successfully inside the REST client. Due to this I am probably going to have to switch to postman. 

## Expected outcome
Spaces are accepted in request URL's and converted to a format the server can receive

## Actual outcome
400 bad request - all of my test data is unusable without conversion

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. Make a call to a service with a URL containing spaces
2. Receive HTTP 400 bad request error
3. Cry

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.

To encode URL please, use dropdown menu on the right of the URL field.
I rethinked this behavior during redesign. Since this is a developer tool to debug how web services behaves in different situations I decided not to alter or change user data in any way. It includes URl field as well. As per debug tool it is wrong behaviour because you may want to test how the errored request would looks like and in old app it wasn't possible.

I'd be inclined to close this as WAI but naturally I'm open for discussion.

**Comment by ependergrass** [comment]
Seems this could be an option instead of forcing it, due to this making all of my testing URL's I had archived useless I had to change to use another tool. :(
