### ISSUE TITLE
Network statistics

### ISSUE THREAD

**Issue by ishant-barnwal** [jarrodek/ChromeRestClient#631]
Earlier, when the client opened within chrome, F12 allowed us to view network statistics so as to demarcate areas, where the API could be performing slow. This does not work any longer as the client is now a separate app and not within chrome.
Could you provide a way to get these statistics?

## Versions
App: 7.9.29.179-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
App is not a part of Chrome anymore. I mean all Chrome apps aren't. Furthermore the app is using socket instead of XHR object. 
Actually the app is now collecting some stats about the request and response timing. It's stored in the database but there is no UI to check it.
The stats looks like regular HAR timing object:
```
{
  blocked: -1,
  comment: null,
  connect: 0.885000000009313,
  dns: -1,
  receive: -1,
  send: 0.834999999962747,
  wait: 2.42500000004657
}
```
Where:
- blocked - the timing does not apply to this request since there is no blocking
- dns - the timing does not apply to this request since the app can't get this information
- connect - Time required to create TCP connection. 
- send - Time required to send HTTP request to the server.
- wait - Waiting for a response from the server.
- receive - Time required to read entire response from the server (now it is not implemented correctly and will be fixed in the future).

As for right not it is inside the database. You can use [debugging](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) to access chrome dev tools and the database but it will be very inconvenient. 

The issue will be fixed soon by adding a timing info to the UI.

**Comment by jarrodek** [comment]
I modified the milestone because it was on my todo list from a long time. It will be hotfixed.

**Comment by ishant-barnwal** [comment]
That would be great.

Thanks,
Ishant
