### ISSUE TITLE
History Saved when the app was on web has vanished

### ISSUE THREAD

**Issue by Amaresh** [jarrodek/ChromeRestClient#637]
The history I saved when the app was on web browser is not there after the migration to desktop app.

## Expected outcome
The same history should have gotten imported here.

## Actual outcome
All history was gone and even after signing in, not imported.

## Versions
App: 7.9.29.179-stable
Chrome: 50.0.2661.86
Platform: Linux (-)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. 
Can you please send a logs from the console for both stat-up and when switching to "saved" screen.
The data are there because there were no data structure change in saved requests store. There must be some error when you trying to read the data. And it's happening when some particular conditions are meet because as I can see in different issue reports history and saved list is working.
Check this [wiki](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) to learn how to debug app.

Thanks

**Comment by jarrodek** [comment]
Please, see the issue #391. I'm closing this as a duplicate.
