### ISSUE TITLE
Connection error through proxy

### ISSUE THREAD

**Issue by coolerl** [jarrodek/ChromeRestClient#639]
Hello,
The pervious version of ARC was working fine by using the proxy settings in the Chrome browser.
However, with this new pop-up version, the client does not use the proxy weather it is configured system wide or just when starting Chrome.

## Expected outcome
Connection should work fine through the Chrome/System set proxy

## Actual outcome
With proxy configured, ARC tries to connect directly to the URL, ignoring the set proxy.
net::ERR_CONNECTION_TIMED_OUT

## Versions
App: 7.7.26.168-stable
Chrome: 49.0.2623.112
Platform: Windows (7)

## Steps to reproduce
1. Configure Chrome/System Wide proxy
2. Open Chrome and start ARC
3. Try to connect to a host through the configured proxy.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. 
I'm aware about the issue but I don't have a fix for that right now. This is caused by separating Chrome apps from Chrome entirely - also from network settings. So calls made from Chrome apps are not respecting network settings. I don't even know if I got this right.
Anyway, check https://bugs.chromium.org/p/chromium/issues/detail?id=172285#c25 for the underlying issue on CR bug. 

I hope I'll be able to bring a good news soon.
