### ISSUE TITLE
I can´t see my old projects that was stored using the old advanced rest client.

### ISSUE THREAD

**Issue by TobbeD** [jarrodek/ChromeRestClient#641]
Copy of log.
![image](https://cloud.githubusercontent.com/assets/18715266/14888308/f724b18e-0d59-11e6-8a37-fbe369174040.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Can you please try to [debug](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) the app and see in Chrome Dev Tools is there are data in your database?
Since there was no change in a database structure it should still be there. I'm looking for any error message.

Thanks

**Comment by TobbeD** [comment]
This is what is see from the the log. Hope it helps you.

Regards Torbjörn

[image: Infogad bild 1]


2016-04-28 13:57 GMT+02:00 Paweł Psztyć <notifications@github.com>:

**Comment by jarrodek** [comment]
Hi,

Thank you for your effort. However GitHub is not processing images and I can't see the image. Can you paste the text instead or paste image in GitHub's editor?

Thanks

**Comment by jarrodek** [comment]
Please, see the issue #391. I'm closing this as a duplicate.
