### ISSUE TITLE
Large response is truncated

### ISSUE THREAD

**Issue by ABogdanovski** [jarrodek/ChromeRestClient#645]
A large response - some 36Kb - is truncated.  Consequently, it cannot be displayed as JSON.
"There was an error parsing JSON data"

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
Is this the same issue as #640?

**Comment by ABogdanovski** [comment]
Hi, Pawel.

Maybe.  I did not page down with "Show next 500 lines", I selected "Show
all".

It started when I got an error trying to display response in JSON.  It
failed.  Then I went to see the whole reply and discovered is truncated.
The last name starts with a quote, but ends unfinished, i.e.
"xx_field_r

 I suppose the server returned the correct data, because of the return code
200.  I see no errors on the server side.  The response is large, some 1800
variables, can total more than 60K.  This truncation happens consistently.

I have a few other servers with the same application, I'll test the ARC
client there and report.

Regards,
Atanas

**Comment by ABogdanovski** [comment]
Pawel, the apps on the other servers had changed the invocation, I cannot check them, for now.  Please try to reproduce the issue with a large reply.

**Comment by eslocum** [comment]
I'm having the same issue.
The response content is being truncated for large results.
It appears to truncate after 8192 characters have been displayed.

**Comment by ABogdanovski** [comment]
Pawel, I counted the bytes: It truncates at 32768 bytes = 32K.

**Comment by ABogdanovski** [comment]
Also, in the real client app that uses the service, they get the full response.  So it is only here where it is truncated.

**Comment by jarrodek** [comment]
Hi,

@ABogdanovski is the response is chunked transfer encoding? If yes it may be the same issue as #640. I can't reproduce the problem even on big responses. When you try urls like `http://httpbin.org/range/40960` it works as intended (reads 40K data in this case). Otherwise it must be something else but I can't diagnose the problem. You may try [debug](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) the app yourself and see what's happening. The transport library is a SocketFetch class included into elements/elements.js script.

**Comment by ABogdanovski** [comment]
Pawel, sorry I didn't have time to look at this sooner.

The response is chunked:
Transfer-Encoding: chunked

Do you have a solution for that?

Regards, 
Atanas

**Comment by jarrodek** [comment]
Still don't. I can't reproduce the problem and I'm trying to figure out the test cases for this issue. I think that chunked transfer encoding and chrome socket buffer may interfere with my code. 
My assumption is that sometimes it may happen that the socket's buffer end in the place where next chunk size has been added to the source. In this case the library may assume that chunk has ended and there's  no more information about the next chunk so it calls response's end because this is what it means in terms of the HTTP spec. This may be an issue and I want to investigate it but I have trouble with test scenarios that can detect the issue.
I'll start working on it anyway.

**Comment by jarrodek** [comment]
The issue can be illustrated in this flow chart:
![image](https://cloud.githubusercontent.com/assets/3320020/17021714/9f40db4e-4f41-11e6-9956-97fe1935b72d.png)
When you add that Chrome has it's own buffer and the data stream could break at any time regarding the chunk size it makes the issue. At least in theory. 
I need do some tests first.

**Comment by jarrodek** [comment]
Latest update in a develop branch should contain fixed code from the `socket-fetch` library.
