### ISSUE TITLE
Why did you ruin rest console?

### ISSUE THREAD

**Issue by fresh83** [jarrodek/ChromeRestClient#659]
from a convenience and UX experience you have ruined the best chrome extension there was, please allow me to roll back. This is so horrid. Everything takes several more clicks, how arrogant to feel you need a entire apps worth of space instead of just a tab.

**Comment by fresh83** [comment]
Want to find a api call....nah you dont, BUT LOOK HOW PRETTY OUR NEW FONT IS!!!!!  
http://imgur.com/zsWJRN1
Want to search for something?  that will be x2 extra clicks

Want to open in browser?  pshhh....were way to important for that. The personality your app now exudes is Kanye West.

**Comment by Izuzusama** [comment]
http://restforchrome.blogspot.sg/2016/04/advanced-rest-client-is-not-in-tab.html

**Comment by jarrodek** [comment]
@fresh83 Thank you for an opinion.

From my side I can add that:
* layout of the app is basically the same. There are some changes (like the left panel now collapses at some point) but I tried not to change many things
* as referenced by @Izuzusama I had no choice upgrading the app
* you can search for a saved request as you were able to do it earlier

Because there's no actual question or issue that I can fix I'd be inclined to close this issue as WAI.

**Comment by fresh83** [comment]
Also....
•Cant click a api request from history alll the way across the line which is REALLY annoying.
•Cant adjust column sizes from history 
•The clear button should be hidden or put behind several clicks. There is nothing worse than clearing it on accident, i realize their is a confirmation, but it still happens bc of it being placed where it is and its enough to make a grown man cry when it does .


Look im obviously this upset bc i loved the app prior, id be willing to pay for a browser version , the last thing devs with lots of apps open need is their web work to be happening in 3 programs instead of 2 (editor,browser,rest console....better would be 1)  Im not against the update , but I have a hard time believing that you could not allow the option to let the app be opened in a tab. 


The design is pretty, I can appreciate that but you went a bit tooo appleish for the crowd you appeal to , we dont need or care about pretty all that much, you came up and got where you are by being super functional. Remember your roots. 

Consider all my bullet points on this comment and op as the ongoing issues im reporting due to a lack of alternative mediums to express the frustration.

**Comment by Izuzusama** [comment]
I would suggest you to create an issue for each bullet point you have. And make sure there are no duplicate on the way.

I like the browser tab thing but the developer has no choice in this. If you would like to complain, you can complain to chromium, but they have their reason too https://blog.chromium.org/2014/06/migrate-your-legacy-packaged-apps-to.html

And since this is an open source project, you can always contribute.

**Comment by fresh83** [comment]
2 words....web-app

**Comment by fresh83** [comment]
it just keeps getting better lol....http://imgur.com/XqJ9TZq

**Comment by jarrodek** [comment]
Hi,

Please, clear this issue up because I'm not sure where to start. One problem per issue report so it can be addressed properly.
I'm closing this as invalid.

**Comment by fresh83** [comment]
of course you are....bc you know you abused success man. Just give us back
old rest as a web app man.

**Comment by fresh83** [comment]
or a open repo we can install locally

**Comment by jarrodek** [comment]
For tab version - please review http://restforchrome.blogspot.com/2016/04/advanced-rest-client-is-not-in-tab.html so you'll know why.
Repo is public, open source and it's here. Clone, get, change, send PR as you wish :)

**Comment by fresh83** [comment]
Dude its the internet....anything is possible, maybe not in the chrome
store, but it is indeed possible to allow what im asking.
