### ISSUE TITLE
Equal character is not encoded and just disappears

### ISSUE THREAD

**Issue by etiennegauthier** [jarrodek/ChromeRestClient#662]
The = is just removed from the parameter and not encoded. 

E.g: 
Make a post request with a payload such as:
myThingId=abcd=efgh&someotherstuff=false

## Expected outcome
the = char should remain and/or be encoded properly (%3D)

## Actual outcome
the = char often disappears and is not encoded 

## Versions
App: 7.16.33.191-stable
Chrome: 50.0.2661.94
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.

String `myThingId=abcd=efgh&someotherstuff=false` is not properly encoded `application/x-www-form-urlencoded` payload. There is no surprise that it isn't working on a server.
The app should not automatically transform any data before sending them. It doesn't know your intentions and since it's a dev tool you may want to create an exception. This is why I put encode/decode buttons so you can transform payload on demand. I'm against automatic text transformation and I don't see upside of it.
I can be wrong so I'm open for discussion, but now I think it shouldn't change.

**Comment by 2Frez** [comment]
@jarrodek I think he was talking about encoding string myThingId=abcd=efgh&someotherstuff=false by pressing "Encode payload"
I encoded it in field '"raw payload" and got myThingId=abcd&someotherstuff=false and you can see string lost '=efgh' and doesn't have '=' encoded to %3D
Also I tried string "login=test' select user from users where id='1' -- " and got "login=test'+select+user+from+users+where+id". It lost the last part "='1' -- "
