### ISSUE TITLE
Can't hit API needing session auth

### ISSUE THREAD

**Issue by andrewmeissner** [jarrodek/ChromeRestClient#669]
Previously in ARC, I could log into my service (rundeck, in this instance) using an admin account, then open ARC and through the service's API list user-access tokens.  In this version of ARC, I receive a 403, but if I run the same GET request in chrome in another tab, I get a 200.  If I was only running GET's against the API, I wouldn't worry about that, but I also need to do PUT's, POST's, etc...

## Expected outcome
I should get a 200 from the service instead of the 403 ARC is getting.

## Actual outcome
ARC receives a 403 from the service because the service doesn't see the GET request as part of the authenticated session.  Running a similar GET request in another browser tab will yield the appropriate result.

## Versions
App: 7.16.33.191-stable
Chrome: 50.0.2661.94
Platform: Mac OS X (10_11_4)

## Steps to reproduce
1. Locally install rundeck (as a jar, or docker container, or locally, etc...)
2. login to the rundeck webapp with username:password admin:admin (localhost:4440/)
3. In another browser tab, get the user tokens from rundeck (localhost:4440/api/17/tokens) 
4. In ARC, run the same GET in step 3 and you'll get a 403 instead of a 200.

**Comment by jarrodek** [comment]
Hi,

Thank you for your issue report.

Because ARC is [not running in tab mode anymore](http://restforchrome.blogspot.com/2016/04/advanced-rest-client-is-not-in-tab.html) it also do not share session with Chrome. It's a standalone app. This is how Chromium team designed it and there's a little I can do about it.

There are various ways to make it work. You can set up a cookie in the request (I'm guessing the session is cookie based). But this will work only for current request. To set a cookie in the app for all requests for this endpoint you should make this first request inside the app passing login and password data as a form. Then backend set the session and send cookies. The app will read it and use in next requests.

Thanks.

**Comment by andrewmeissner** [comment]
Thanks for your input!
