### ISSUE TITLE
Error parsing XML

### ISSUE THREAD

**Issue by cmschofield** [jarrodek/ChromeRestClient#691]
When parsing the result XML (copied from ARC Raw tab):

`<feed xml:base="https://test.domain.com" xml:lang="en" xmlns="http://www.w3.org/2005/Atom"><id>urn:uuid:f82dc2a7-2ca0-4414-91f6-2ff1e025e165</id><title type="text">System On-Demand</title><updated>2014-08-20T05:00:00Z</updated><author><name>System</name><uri>http://domain.com/</uri></author><category term="J45" scheme="mainSearchCriteria.v.c" /><category term="2.16.840.1.113883.6.90" scheme="mainSearchCriteria.v.cs" /><subtitle type="text">System On-Demand Infobutton Results</subtitle><entry xml:lang="en"><id>tag: test.domain.com, 2014-20-08:/HealthSheet.aspx3,82427</id><title>Asthma, Understanding</title><updated>2014-08-20T05:00:00Z</updated><link href="https://test.domain.com/HealthSheet.aspx?id=82427aa&amp;ContentTypeId=3&amp;type=custom&amp;AccessToken=B4L385DM5DQHZA5Z766MBJN01" rel="alternate" type="html" hreflang="aa" title="Asthma, Understanding" /><link href="https://test.domain.com/HealthSheet.aspx?id=82427&amp;ContentTypeId=3&amp;type=custom&amp;AccessToken=B4L385DM5DQHZA5Z766MBJN01" rel="alternate" type="html" hreflang="en" title="Asthma, Understanding" /><summary type="html">&lt;p&gt;Asthma disease description</summary><category term="J45" scheme="mainSearchCriteria.v.c" /><category term="2.16.840.1.113883.6.90" scheme="mainSearchCriteria.v.cs" /></entry></feed>`

I get the following error:

There was an error parsing XML data
NAMESPACE_ERR: The namespace declaration is incorrect

## Expected outcome
I believe this XML is valid as I've checked it with several validators and with C# XML libraries. I'm not sure what the issue is.

## Actual outcome
Received the error:
There was an error parsing XML data
NAMESPACE_ERR: The namespace declaration is incorrect

## Versions
App: 7.20.37.203-stable
Chrome: 50.0.2661.102
Platform: Windows (7)

## Steps to reproduce
1. Well, everything is running locally for me. I'm not sure you can reproduce it?

**Comment by jarrodek** [comment]
Thanks for an issue report.

It looks like the [xml.js liblary](http://xmljs.sourceforge.net/index.html) used to parse XML document result with exception. After some digging I noticed that the proper namespace declaration should looks like `xmlns:base` instead of `xml:base`. This attribute causing the problem. 
Please, check documentation for namespace declaration https://www.w3.org/TR/xml-names/#ns-decl, especially: 

> The prefix xml is by definition bound to the namespace name http://www.w3.org/XML/1998/namespace. It MAY, but need not, be declared, and MUST NOT be bound to any other namespace name. Other prefixes MUST NOT be bound to this namespace name, and it MUST NOT be declared as the default namespace.

I can guess that other parsers in C# do not respect this rule. It doesn't change that it's wrong declaration and therefore it should not be used. Other libraries may not have this exception and your code will break. 

Taking it into the account I'd be inclined to close this issue as WAI.

**Comment by cmschofield** [comment]
OK. Thank you for the information. I'll get it fixed in our XML parser.

**Comment by pzieminski** [comment]
The attribute xml:base is correct and defined here
https://www.w3.org/TR/xmlbase/

**Comment by jarrodek** [comment]
The example above will now work properly in ARC.
See #719 for more information.
