### ISSUE TITLE
Save response content to file not working properly when saving binary data

### ISSUE THREAD

**Issue by targetoid** [jarrodek/ChromeRestClient#704]
The "Save content to file" button in response panel appears to be saving the response data in text format rather than binary.

## Expected outcome
Response binary data are saved exactly as they arrived.

## Actual outcome
Values that are not valid UTF-8 characters are being replaced by "�" characters (EF BF BD in hex) in the output file.

# Versions
App: 7.20.37.203
Chrome: 51.0.2704.84 m

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. Right now there's no support for binary data. All is converted to string. 
It may be fixed in the future but - to be honest - it has low priority right now. Use case is rather rare and the app is not intended to download binary data. I do recognise that there is a use case for that but I have very limited resources to develop the app. 

Thanks

**Comment by ericpyle** [comment]
I have encountered the same issue. I would like to test that my api produces a proper zip package.

At the very least, perhaps ARC could display a warning when clicking "Save content to file" that indicates that the content is binary and won't be saved properly.
