### ISSUE TITLE
Problem with header values containing '=' and ' '

### ISSUE THREAD

**Issue by monami555** [jarrodek/ChromeRestClient#716]
Hello

I am using "Data form" header view. When I save a request that has the following header value:

    test.test=test bla=bla

and open the saved request again, instead of the above it has this value stored:

    test.test

I suppose this has something to do with encoding special characters, it should be done also when I use the "Data form" view. Only saving such request doesn't work, executing it works as expected.

Monika

**Comment by jarrodek** [comment]
Hi,

Thank you for an issue report.
Partially the app is working as intended. The payload (request body) in the x-www-form-urlencoded content type (regular web form) need to be [url encoded](https://en.wikipedia.org/wiki/Percent-encoding) in order to properly send it. The app is not doing it for you because in this case it can unambiguously detect parameter name and value. 
To encode values to fit x-www-form-urlencoded media type encoding you should use `Encode payload` button above the form. 

And here's an issue actually. After encoding value of `test.test=test bla=bla` it will paste back `test.test` only. It's a parser error. It should replace both equal signs to `%3D` and space to `+` sign. However it must be manual action of the user.
