### ISSUE TITLE
Parsed view of the response has word wraping on by default

### ISSUE THREAD

**Issue by RanGold** [jarrodek/ChromeRestClient#733]
Could you add the ability to switch word wrap off?

**Comment by jarrodek** [comment]
Hi,
Thank you for issue report.
I'm not sure if you referring to removing a wrapping at all or about the issue with word break. If the later, the words shouldn't be wrapped by breaking the word. If you'd like to remove wrapping at all then I'm not sure if this is the best idea because users would need to scroll a lot to see the output. It's easier to scroll up-down than left right so I don't see a need for change.

**Comment by RanGold** [comment]
Hi,
I just want the option to turn it off, same as in the "Raw" view

**Comment by jarrodek** [comment]
The "raw" response view is now always visible.
