### ISSUE TITLE
Can't use with '&' in cql.

### ISSUE THREAD

**Issue by SaraIsraeli** [jarrodek/ChromeRestClient#739]
Hi,
When I try to use with '&' in cql, I get incorrect syntax error.
 
Cql:
tq=select count(distinct ip) as Amount, search_location, search_term,device_type,     affiliate_id,search_landing_source, day(event_time_ts) as Day, month(event_time_ts) as Month, year(event_time_ts) as Year
from cooladata
where date_range(between 2016-06-01 and 2016-06-30)
and search_landing_source in ("&")
group by 2,3,4,5,6,7,8,9

Note, I success to run the cql in bq .

![image](https://cloud.githubusercontent.com/assets/20552877/17353640/16d1a2d0-594a-11e6-96d9-388569bcc7ae.png)

Thanks, Sara.

**Comment by jarrodek** [comment]
Hi Sara,

Thank you for the issue report. 
You are using `application/x-www-form-urlencoded` content type but you haven't encoded the payload. There are two buttons above the payload form. When you use "Encode payload" then it will replace all characters according to the HTTP specification. 
It must be manual action if you use "raw" input.
Otherwise it works as intended.

**Comment by SaraIsraeli** [comment]
Hi Jarrodek,
I get same error also if I have encoded the payload. 
-Sara.
