### ISSUE TITLE
Json is not parsed nice any loger

### ISSUE THREAD

**Issue by peterivarsson** [jarrodek/ChromeRestClient#766]
Hi,

Previous version had a better JSON parsing, It is difficult to see the Jason data.

<img width="890" alt="skarmavbild 2016-08-24 kl 15 43 12" src="https://cloud.githubusercontent.com/assets/13362021/17932834/1f84b682-6a12-11e6-9df5-870702850f3a.png">

**Comment by jarrodek** [comment]
Hi,

Nothing has changed in this area.
I can see that the response content type header is correct. In this case the JSON viewer was enabled and tried to parse data and display it but there was an error in JSON. Fallback procedure in ARC is to show "parsed" tab instead of "JSON"'s because "parsed" uses different highlighting mechanism. If you analyse the response you'll see that there's an error in it. 
There's no other way for the "parsed" tab to be displayed instead of "json" but when there's  a parser error.
I'd be inclined to close this issue as WAI.
