### ISSUE TITLE
Try to use DELETE with a resource that returns 204 AND return data, hangs extension

### ISSUE THREAD

**Issue by claudiobastos** [jarrodek/ChromeRestClient#787]
I made an endpoint which returns HTTP Status Code 204, and the json {"code":204,"message":"No Content"}

The same happens if I try to use 205 as http status code.

## Expected outcome
What should happen?
It should show the content, or at least the headers.

## Actual outcome
What happened?
It hangs

## Versions
App: 7.31.45.225-stable
Chrome: 53.0.2785.92
Platform: Linux (-)

## Steps to reproduce
1. Create a script that returns http status code 204 and the above Json
2. Try to access it with DELETE method
3. 

Extra info: If I use 200, 201, 202,203,206,207 as Status Code it works.

**Comment by jarrodek** [comment]
Thank you for the issue report. I'll get into this this week.

**Comment by jarrodek** [comment]
As for the 204 response there's a part of the spec:

> A 204 response is terminated by the first empty line after the header
   fields because it cannot contain a message body.

Therefore this kind of response can't contain any response payload and the app is obligated to drop any payload from it. See https://tools.ietf.org/html/rfc7231#section-6.3.5 for more details.

Same thing for 205 status code:

> Since the 205 status code implies that no additional content will be
   provided, a server MUST NOT generate a payload in a 205 response. 

I've tested if this response status result with the headers and the response headers are returned and displayed correctly. I'd be inclined to close this issue as WAI.
