### ISSUE TITLE
I want to sort the drop down meny for the project in alfabetic order

### ISSUE THREAD

**Issue by peterivarsson** [jarrodek/ChromeRestClient#816]
I want to sort the drop down meny for the project in alfabetic order (Like I have it now its a mess with a lot of duplicates).
So I would also want to remove the duplicates.

Is there a way to sort the drop down (It would be nice if that was automatically done)?

Is there a way to delete items from that meny?

See picture below
![skarmavbild 2016-10-12 kl 07 51 09](https://cloud.githubusercontent.com/assets/13362021/19298979/c2eafbbe-9051-11e6-96f1-9204d43e47a1.png)

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
There's no automatic sorting. Items on the list are sorted according to their add date. I'm not planning adding it right now because people probably get used to the sort order on their lists and changing it right now doesn't feels right. I do however keep it in mind to do the change during next UI update.

You can delete project endpoints by going to the project page. On the projects list click on a pencil next to the project name. On this page you'll be able to delete endpoints.

Thanks.

**Comment by jarrodek** [comment]
In the new version (v8) it will be as suggested. Resources names in the drop down list will be sorted. The update will arrive to the stable channel in coming days.

**Comment by peterivarsson** [comment]
HI,

Tanks this works terrific.
It makes my job easier.

TANKS agaan.

/ Peter

Från: Paweł Psztyć <notifications@github.com>
Svara till: jarrodek/ChromeRestClient <reply@reply.github.com>
Datum: måndag 7 november 2016 13:48
Till: jarrodek/ChromeRestClient <ChromeRestClient@noreply.github.com>
Kopia: Peter Ivarsson <Peter.Ivarsson@cybercom.com>, Author <author@noreply.github.com>
Ämne: Re: [jarrodek/ChromeRestClient] I want to sort the drop down meny for the project in alfabetic order (#816)


In the new version (v8) it will be as suggested. Resources names in the drop down list will be sorted. The update will arrive to the stable channel in coming days.
