### ISSUE TITLE
Install self signed certificate in Chrome

### ISSUE THREAD

**Issue by zhrist** [jarrodek/ChromeRestClient#829]
When I tried to call service over https I got this error:
Install self signed certificate in Chrome

The app can't work if the self-signed certificate is not installed in Chrome.

TELL ME MORE
net::ERR_CERT_AUTHORITY_INVALID

The problem is that service is self signed, but when I installed cert into chrome it works fine in chrome.
However, it still throws this exception in ARC.
 
Your description here

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 7.39.48.260-stable
Chrome: 54.0.2840.59
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report.
It's not an issue related to app particularly but to Chrome apps in general. It's out of scope of this project and it's a Chrome team issue.

As a workaround, please, refer to this blog post: https://restforchrome.blogspot.co.uk/2016/04/advanced-rest-client.html

Essentially you have to use "Use XHR" option (in main UI) to proxy the request via Chrome extension. Then it will work. Otherwise self signed certificates will never work in Chrome apps.

Nothing more I can do about it since Chrome team is persistent on not relaxing certificates policy for apps (what is understandable from the security perspective of all whole apps ecosystem).
I'm closing it as WAI.
