### ISSUE TITLE
Missing all Projects, Request URLs, History, etc. in New Version of ARC

### ISSUE THREAD

**Issue by donstrong** [jarrodek/ChromeRestClient#899]
Hi, how can I restore the many hundreds of requests that were stored under various projects and saved to the local datastore?  I was not storing them on GoogleDrive nor was I aware that a new push of ARC would erase them.  Had I known in advance, I could've exported to a file!!  Please help me restore my projects and requests.  Thanks!

**Comment by jarrodek** [comment]
Hi,

There should be no issue with the data. The data are there because upgrade script was never meant to delete any data.
Please, [debug](https://github.com/jarrodek/ChromeRestClient/wiki/debugging) the app and paste here any console message so I can try to help you.

**Comment by Nandav1** [comment]
Hi I have the same problem. Actually I upgrade my laptop with windows 10 unfortunately it did not go well and my project gave me a new hard disk. So If you please tell me the disk location where the projects are saved, I can request the tech support to send me that data from the old hard disk.

Thanks,
Nanda

**Comment by jarrodek** [comment]
Hi @Nandav1 
This is different issue - not related to this one. No need to set up new one because I won't be able to help you.
The data are stored in the IndexedDb, under your profile (if you had only one profile on Chrome then it will be Default Profile). Anyway, somewhere in the profile directory you have a folder where databases files are stored. You'd need to move this files (from old disk) to new one to the same location.
I can't help you more, I'm not sure if this could work (e.g. if there's any kind of encryption enabled in the database files) and where to find particular files. I can only tell you that the app's folder will be named "hgmloofddffdnphfgcellkdfbfbjeloo" (app ID) and it will contain the files.

I'm sorry but I can't help you more.

**Comment by jarrodek** [comment]
I'm closing this issue but feel free to reopen if needed.
