### ISSUE TITLE
关于保存问题

### ISSUE THREAD

**Issue by gametheworld** [jarrodek/ChromeRestClient#902]
为什么按ctrl+s不是弹出保存框了？改变操作习惯很不爽，已经弃用了！！！

**Comment by jarrodek** [comment]
If Google translate translated this correctly then...

CTRL + S and CTRL + SHIFT + S are commonly used commands on every OS (in macOS there's a command instead of ctrl). The app was inconsistent with this affecting UX. Latest update fixed this issue and now app works as it intend to work. 
You shouldn't to learn new habits when using a specific app and ARC was breaking habits. As I stated some time ago, the app must comply with standards (not only web standards this means).
Therefore I'd be inclined to close this issue as WAI.
