### ISSUE TITLE
Can not find saved requests

### ISSUE THREAD

**Issue by maxifly** [jarrodek/ChromeRestClient#903]
Your description here
Press "Saved"
Choose icon "Search"
  Type part of request name
  press enter

## Expected outcome
Look short list of saved requests wich name like of entered mask

## Actual outcome
Look one saved request wich name not like of entered mask

## Versions
App: 8.14.55.288-stable
Chrome: 54.0.2840.99
Platform: Windows (7)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

I can't reproduce this. What name you are trying to enter? 

And let me paraphrase the steps:
1. Press save icon in the toolbar
2. Enter the name in the name field 
3. Press save button to save the request with new name

In the saved list screen the name is different than the one you have entered in the field in step 2. Is this correct?

**Comment by robwe** [comment]
I have the same problem. I select on the lift side the "Saved" option. Then on the right side I can see all my saved queries. Then I select in the top right corner the "Search" icon and enter a search text and press Enter. I get the response "The list is empty". The entered search text is contained in some descriptions and/or urls of my queries, but I do not get the matching items. Instead I get the empty list message. I am using version 8.14.55.288 on Windows 10 and the problem came with the last update.

**Comment by lavuy** [comment]
Hi, 
I've got the exact same issue as robwe.
Thanks!

**Comment by jarrodek** [comment]
@robwe and @lavuy The issue you are describing is already patched but it's tested right now. I'll release an update in next 2 days or so. 
However issue reported by @maxifly it somewhat different. I'm not sure yet how.

**Comment by dunght160387** [comment]
Yes, the most basic could not work properly.

**Comment by jarrodek** [comment]
The issue described here was patched some time ago. The search was redesigned in the history / saved panel.
