### ISSUE TITLE
Displaying long value in JSON is incorrect

### ISSUE THREAD

**Issue by jehof** [jarrodek/ChromeRestClient#921]
I have a json response that contains the following number value (int64, long) **93514409221029891**. When I view the json response as RAW I see the number as expected, but when I change the display format of the response to JSON the number is displayed as 9351440922102989**0**.  So there seems to be an issue how the data is displayed in the JSON view.

The number is contained in a fairly big response (array with 100 elements) and each element has a nesting structure if its relevant.

*JSON-View*
![jsonview](https://cloud.githubusercontent.com/assets/1583129/20916292/46433256-bb8b-11e6-9568-100afaf4526d.png)

*RAW-View*
![rawview](https://cloud.githubusercontent.com/assets/1583129/20916293/4643f77c-bb8b-11e6-8307-d5c4dad1b03d.png)

**Comment by PGeffriaud** [comment]
I think that your error is directly linked to the following issue #234 which is now closed.

**Comment by jarrodek** [comment]
Hi,

Thank you for issue report. 

Yes, it was fixed. But as much as I can see in this case it isn't working.  The app **should** display incorrect value (result from JSON.parse function) but also a warning with information that long values shouldn't be used in APIs because JavaScript can't handle it properly and alongside with this explanation a value that is in the original JSON response.

I'm marking this as a bug and I'll see what I can do about this.

**Comment by jarrodek** [comment]
This issue should be resolved in the latest version where the warning message for long values were added when the Number is greater than maximal number representation in JS.
I'm closing this issue but fell free to reopen if needed.
