### ISSUE TITLE
Invalid Json Decode

### ISSUE THREAD

**Issue by skmohammadi** [jarrodek/ChromeRestClient#930]
Hi. I want to send following data Using Put method to an API:
`{
    "is_receiving_support_notifications": false
}`
when i copy and past the above code in Raw payload input, the app convert the code to:
`{    "is_receiving_support_notifications"=false`
and give me following error:
`{
"success": false,
"error": {
"message": "Expecting : delimiter: line 1 column 41 (char 41)",
"code": "request_decode_failed"
}
}`

**Comment by zypperin** [comment]
you should paste the PUT data in Raw payload area not the header

**Comment by skmohammadi** [comment]
@zypperin excuse me, the issue updated!

**Comment by jarrodek** [comment]
Hi,
Thank you for the issue report.

I was trying different configurations, options and buttons and only once I was manage to make the result as you've described. It was when I set the content-type to `application/x-www-form-urlencoded` and then by pressing the "decode payload" button. But in this case, it is expected behaviour. 

Have you set the `application/json` header in the headers list or in the content type dropdown list?

**Comment by skmohammadi** [comment]
No. its needed?

**Comment by jarrodek** [comment]
Basically, this is how clients and servers communicate what kind of payload they are carrying. 
It may be a UX thing, but basically, the app can't be sure what you are trying or intend to transport. It can be JSON, XML, text, Form data, file, and hundreds of other types. So the final decision is to be made by the user. The app does not alter the request in any way. 

Try setting up this header and let me know if that helped.

**Comment by jarrodek** [comment]
Is my last comment helped resolving this issue?

**Comment by jarrodek** [comment]
I'm closing this issue. Reopen if needed.
