### ISSUE TITLE
[Question] Can i send a request that without 'Host' header?

### ISSUE THREAD

**Issue by syuilo** [jarrodek/ChromeRestClient#934]
Hi guys. I want to send an HTTP request that without `Host` header for debugging of my server. Can I do it?
--- Thanks for this great App. Cheers

**Comment by jarrodek** [comment]
Hi,

Thank you for the question.

Well, basically you can't when using this app. Although it is possible (according to the spec) to send the Request with an absolute URI but the app will always split it into the path and host header. This is how the transport library was made.
So it always gonna be something like:
```
GET /get HTTP/1.1
HOST: httpbin.org
```
instead of 
```
GET httpbin.org/get HTTP/1.1
```
It could be changed in the transport library but this change is quite big and I can't afford to do it right now. I hope you understand.
It may change in the future but as for now I'm not planning to change this behavior.
