### ISSUE TITLE
Should pop up "overwrite or new" when Save

### ISSUE THREAD

**Issue by dunght160387** [jarrodek/ChromeRestClient#939]
I see this feature is remove from new version.
When Ctrl+S to save, i think it's better if we pop up dialog to select action overwrite or save as new.
It's not a big problem, but it makes user avoid miss take when creating new from an existed rest.

## Expected outcome
pop up dialog to select action overwrite or save as new

## Actual outcome
Only save

## Versions
App: 8.19.60.296-stable
Chrome: 53.0.2785.143
Platform: Linux (-)

## Steps to reproduce
1. create new rest
2. edit rest above to make new rest similar a bit
3. if ctrl+s instead of ctrl+shift+s => overwrite old rest. i lost it.

**Comment by jarrodek** [comment]
Hi,

If you press ctrl+s on unsaved request then the popup bill be displayed by default. However, if the request is restored then the default action for ctrl+s is immediate save instead of showing the popup. You have to use ctrl+shift+s keys combination to display the popup in this case.
This is due to have consistent UX with other application. This is how the ctrl+s and ctrl+shift+s works with most applications.
