### ISSUE TITLE
ARC can't send files on new Chrome version: 56.0.2924.76 (64-bit)

### ISSUE THREAD

**Issue by silvioprog** [jarrodek/ChromeRestClient#945]
Hello,

After installing my Chrome to 56.0.2924.76, ARC can't send files using content-type application/form-data.

My environment:
Windows 10 64 bits.
Chrome 56.0.2924.76 (64-bit)
ARC 8.19.60.296

Thank you!

**Comment by jarrodek** [comment]
Hi,

Thank you for the issue report.
It's confirmed bug in Chrome (https://bugs.chromium.org/p/chromium/issues/detail?id=688100)

However, it forced me to start working on new way of sending the files in ARC which is long pending task on my list. The work is already ongoing but there's a lot to implement so it will take some time. I'm planning to finish this this month but so far I can only getting into another issues so I'm not sure about this anymore. I'll notify you here when the fix moves from the dev branch and will be ready to be tested and released.

**Comment by iamsid** [comment]
Any update? File upload still not working on Chrome 56.0.2924.87 (64bit) with ARC 9.14.64.305.

**Comment by jarrodek** [comment]
Hi,

I'm working on changing the implementation. But it's a core of the application and it has some implications (storing history data, saved requests, making a request itself) and it's a lot of work to do. Also I'm combining this with a long waited changes to the files panel.
I still need few days to finish it.

**Comment by silvioprog** [comment]
Finally I solved the problem using a workaround: enable the `Use XHR` option and remove the header `Content-Type: multipart/form-data`. Thank you!

**Comment by jarrodek** [comment]
Interesting workaround. However it doesn't fix the issue. I'm reopening it because I'm still working on new Files sending implementation.

Quick update:
- I was able to recreate file sending mechanism in the app with new Multipart object that behaves similar to the `FormData` object but has few additional function I am using with forms. And it doesn't have this bug that started the whole thing
- I was able to save files send to an endpoint in requests history
- I was able to restore the files from history when restoring the history item
- I was able to create a new view for the request body - this is totally new view, without a tabs (which are really bad idea) and with new multipart editor (alongside the files you'll be able to send regular form data as well).

TODO:
- the same thing as for history must be done for saved requests
- measure performance change when using files saving / restoration
- find a way to reuse already stored files with multiple requests that have been sending the same file (to not store the same file multiple times)
- Test the whole thing and hope it will not broke the app :)

I was away for past 3 weeks and I couldn't done it earlier. However I'm going back to the project (hopefully) tomorrow.

**Comment by iamsid** [comment]
Any update? File upload still not working on Chrome 58.0.3029.110 (64-bit) with ARC 9.14.64.305.

**Comment by dunght160387** [comment]
I have this issue too, same as @iamsid. Please fix the bug. Thank you!

**Comment by jarrodek** [comment]
Today's release have this fixed. (version 10)
