### ISSUE TITLE
Unable to Import earlier used JSON project in Chrome - Rest Client

### ISSUE THREAD

**Issue by AMarvel** [jarrodek/ChromeRestClient#957]
Hello Team,

I am getting below error while trying to import the earlier exported project in Rest Client.

Error:
Data import Error: The file is no longer supported.

## Expected outcome
What should happen?

## Actual outcome
What happened?

## Versions
App: 8.19.60.296-stable
Chrome: 58.0.3013.2
Platform: Windows (8.1)

## Steps to reproduce
1. 
2. 
3.

**Comment by jarrodek** [comment]
Hi,

The fix is on the way. You can test it (please do) in ARC beta channel. Join the beta testers group here: https://groups.google.com/forum/#!forum/advanced-rest-client-beta-channel then install the app (joining the group let you see the app in chrome web store). If you won't be able to import the project it means it wasn't fixed.
Stable release will be out in coming days.

Thanks

**Comment by jarrodek** [comment]
The release with fix has been published today.
Thanks for reporting the bug.
